# frozen_string_literal: true

require 'rubocop/rake_task'
task default: %w[lint run]

RuboCop::RakeTask.new(:lint) do |task|
  task.patterns = ['lib/**/*.rb', 'test/**/*.rb']
  task.fail_on_error = false
end

task :run do
  ruby 'lib/service_bus.rb'
end

task :test do
  ruby 'test/service_bus_test.rb'
end
